apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tekton-pipelines

resources:
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.6/git-clone.yaml
- tasks.yaml
- deploy-func-app.yaml
- service-account.yaml
