apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kubernetes/azure-workload-identity
- kubernetes/nginx
- kubernetes/tekton
- kubernetes/tekton-workload

patches:
- path: patch-azure-workload-identity.yaml
  target:
    kind: ConfigMap
    name: azure-wi-webhook-config
    version: v1
